# Generated by Django 4.2.24 on 2025-09-05 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('total_stores', models.IntegerField(default=0)),
                ('successful_stores', models.IntegerField(default=0)),
                ('failed_stores', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'scraping_sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('prefecture', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_successful_scrape', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ScrapingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapingsession')),
            ],
            options={
                'db_table': 'scraping_errors',
            },
        ),
        migrations.CreateModel(
            name='DailySlotData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField()),
                ('pref_id', models.IntegerField(blank=True, null=True)),
                ('machine_id', models.IntegerField(blank=True, null=True)),
                ('machine_number', models.IntegerField(blank=True, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_difference', models.IntegerField(blank=True, null=True)),
                ('game_count', models.IntegerField(blank=True, null=True)),
                ('payout_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('bb', models.IntegerField(blank=True, null=True)),
                ('rb', models.IntegerField(blank=True, null=True)),
                ('synthesis', models.CharField(blank=True, max_length=64, null=True)),
                ('bb_rate', models.CharField(blank=True, max_length=64, null=True)),
                ('rb_rate', models.CharField(blank=True, max_length=64, null=True)),
                ('data_url', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraping_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapingsession')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.store')),
            ],
            options={
                'db_table': 'daily_slot_data',
                'indexes': [models.Index(fields=['date'], name='daily_slot__date_2f51db_idx'), models.Index(fields=['store'], name='daily_slot__store_i_f6beb6_idx'), models.Index(fields=['date', 'store'], name='daily_slot__date_1b6113_idx'), models.Index(fields=['machine_id'], name='daily_slot__machine_4672d7_idx'), models.Index(fields=['unique_id'], name='daily_slot__unique__075600_idx')],
                'unique_together': {('date', 'store', 'machine_number')},
            },
        ),
    ]
