# Generated by Django 4.2.24 on 2025-09-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyslotdata',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='scrapingsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
